"""initial schema

Revision ID: e174c20003ba
Revises: 
Create Date: 2026-06-20 22:25:24.363259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e174c20003ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_base_1l', sa.Float(), nullable=False),
    sa.Column('delivery_per_extra_liter', sa.Float(), nullable=False),
    sa.Column('reverse_base_1l', sa.Float(), nullable=False),
    sa.Column('reverse_per_extra_liter', sa.Float(), nullable=False),
    sa.Column('storage_rub_per_liter_day', sa.Float(), nullable=False),
    sa.Column('per_liter_bands', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_tariffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_tariffs_effective_from'), ['effective_from'], unique=False)

    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('fbw', sa.Float(), nullable=False),
    sa.Column('fbs', sa.Float(), nullable=False),
    sa.Column('dbs', sa.Float(), nullable=False),
    sa.Column('edbs', sa.Float(), nullable=False),
    sa.Column('cc', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commissions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_subject'), ['subject'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('category_subject', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sales_model', sa.String(length=8), nullable=True),
    sa.Column('delivery_type', sa.String(length=16), nullable=True),
    sa.Column('warehouse_ids', sa.JSON(), nullable=True),
    sa.Column('turnover_days', sa.Float(), nullable=True),
    sa.Column('buyout_percent', sa.Float(), nullable=True),
    sa.Column('promo_percent', sa.Float(), nullable=True),
    sa.Column('other_expenses_per_unit', sa.Float(), nullable=True),
    sa.Column('tax_system', sa.String(length=40), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculations_user_id'), ['user_id'], unique=False)

    op.create_table('warehouse_coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.String(length=120), nullable=False),
    sa.Column('delivery_type', sa.String(length=16), nullable=False),
    sa.Column('logistics_coef', sa.Float(), nullable=False),
    sa.Column('storage_coef', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_coefficients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_coefficients_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_coefficients_warehouse_id'), ['warehouse_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_coefficients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_coefficients_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_coefficients_effective_from'))

    op.drop_table('warehouse_coefficients')
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculations_user_id'))

    op.drop_table('calculations')
    op.drop_table('warehouses')
    op.drop_table('users')
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_subject'))
        batch_op.drop_index(batch_op.f('ix_commissions_effective_from'))
        batch_op.drop_index(batch_op.f('ix_commissions_category'))

    op.drop_table('commissions')
    with op.batch_alter_table('base_tariffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_tariffs_effective_from'))

    op.drop_table('base_tariffs')
    # ### end Alembic commands ###
